spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # 콘솔창에 하이버네이트 실행 SQL을 남김
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남김
#  org.hibernate.type: trace # SQL에 던지는 파라미터를 출력해주는 옵션